/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiltescreen;

/**
 *
 * @author bcturner
 */
public class titleScreenForm extends javax.swing.JPanel {

    /**
     * Creates new form titleScreenForm
     */
    public titleScreenForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        brickGamesBitch = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        teamAndPointsButton = new javax.swing.JButton();
        backgroundLayer = new javax.swing.JLabel();

        setLayout(null);

        titleLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        titleLabel.setText("Welcome to Fraction Interaction!");
        add(titleLabel);
        titleLabel.setBounds(150, 10, 290, 30);

        brickGamesBitch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/brickGameLabel.png"))); // NOI18N
        add(brickGamesBitch);
        brickGamesBitch.setBounds(210, 80, 204, 220);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bubbleGameLabel.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 90, 230, 210);

        teamAndPointsButton.setText("Teams and Points");
        add(teamAndPointsButton);
        teamAndPointsButton.setBounds(440, 360, 160, 29);

        backgroundLayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background.png"))); // NOI18N
        add(backgroundLayer);
        backgroundLayer.setBounds(0, 0, 609, 400);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLayer;
    private javax.swing.JLabel brickGamesBitch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton teamAndPointsButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
